/**
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms
 * will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <gmp.h>

int main(void)
{
    mpz_t s, g1, g2, m;
    mpz_init_set_ui(s, 2);
    mpz_init_set_ui(g1, 2);
    mpz_init_set_ui(g2, 8);
    mpz_init_set_str(m, "4000000", 10);

    while (mpz_cmp(g2, m) <= 0)
    {
        mpz_add(s, s, g2);
        mpz_mul_ui(g2, g2, 4);
        mpz_add(g1, g1, g2);
        mpz_divexact_ui(g2, g2, 4);
        mpz_swap(g1, g2);
    }

    gmp_printf("%Zd\n", s);

    mpz_clear(s);
    mpz_clear(g1);
    mpz_clear(g2);
    mpz_clear(m);

    return 0;
}
